add new parser versions
diablomedia/useragent-parser-comparison pull request #30
Opened 2018-09-14 09:08 UTC by mimmi20

browscap-js has released new major versions.

This PR tries to add these new versions. Additional to that the Lite and Standard mode detections for browscap-php 4 are added.

Some of the parser directories are renamed to add the used language to the directory name.

2018-09-14 23:21 UTC, jaydiablo requested changes

2018-09-14 23:21 UTC, jaydiablo commented on parsers/browscap-php-4-lite/scripts/parse.php
> +//$test = [];
Please remove.

2018-09-14 23:21 UTC, jaydiablo commented on parsers/browscap-php-4-lite/scripts/parse.php
> +//$test = [];
Please remove.

2018-09-14 23:21 UTC, jaydiablo commented on parsers/browscap-php-4-lite/scripts/parse.php
> +$logger    = new \Monolog\Logger('null');
When I was testing this parser, it spit out a lot of output like this:

```
[2018-09-14 23:07:33] null.DEBUG: cache key "browscap.iniparts.d04" was empty [] []
[2018-09-14 23:07:33] null.DEBUG: cache key "browscap.patterns.31" was empty [] []
[2018-09-14 23:07:33] null.DEBUG: cache key "browscap.patterns.db" was empty [] []
[2018-09-14 23:07:33] null.DEBUG: cache key "browscap.patterns.13" was empty [] []
[2018-09-14 23:07:33] null.DEBUG: cache key "browscap.patterns.3a" was empty [] []
[2018-09-14 23:07:33] null.DEBUG: cache key "browscap.patterns.b7" was empty [] []
```

The data seems like it was still ok, as I compared browscap-php-3-lite and browscap-php-4-lite and they returned the same results:

```
| browscap-php-3-lite | 3.1.0-6000030 | 1729/8075 21.41% | 1435/6689 21.45% | 4330/10180 42.53% | 4.139s     | 7494/24944 30.04% |
| browscap-php-4-lite | 4.1.0-6000030 | 1729/8075 21.41% | 1435/6689 21.45% | 4330/10180 42.53% | 6.077s     | 7494/24944 30.04% |
```

But I was curious if it was possible to silence those errors using monolog's NullHandler. Adding the `pushHandler` line below seems to have solved that.

```
$logger    = new \Monolog\Logger('null');
$logger->pushHandler(new \Monolog\Handler\NullHandler());
```

Seems like it should be added here (and probably in all of the browscap-php-4 parsers IMO).  It may be a sign of something wrong with the Lite file's cache in browscap-php-4 (3 does not do this), but since it seems to parse ok, may be nothing.

2018-09-17 06:30 UTC, mimmi20 commented on parsers/browscap-php-4-lite/scripts/parse.php
> +$logger    = new \Monolog\Logger('null');
changed

2018-09-17 06:30 UTC, mimmi20 commented on parsers/browscap-php-4-lite/scripts/parse.php
> +//$test = [];
fixed

2018-09-17 06:30 UTC, mimmi20 commented on parsers/browscap-php-4-lite/scripts/parse.php
> +//$test = [];
fixed

2018-09-17 15:55 UTC, jaydiablo approved these changes

2018-09-17 15:56 UTC, merged

2018-09-17 15:56 UTC, jaydiablo commented
Thanks!